export const textStyles = {
  'text-xs-regular': {
    fontSize: '12px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '16px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xs-medium': {
    fontSize: '12px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '16px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xs-semibold': {
    fontSize: '12px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '16px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xs-mono': {
    fontSize: '12px',
    textDecoration: 'none',
    fontFamily: 'DM Mono',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '16px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xs-underlined-regular': {
    fontSize: '12px',
    textDecoration: 'underline',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '16px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xs-underlined-medium': {
    fontSize: '12px',
    textDecoration: 'underline',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '16px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-sm-regular': {
    fontSize: '14px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '20px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-sm-medium': {
    fontSize: '14px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '20px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-sm-semibold': {
    fontSize: '14px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '20px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-sm-underlined': {
    fontSize: '14px',
    textDecoration: 'underline',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '20px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-sm-mono': {
    fontSize: '14px',
    textDecoration: 'none',
    fontFamily: 'DM Mono',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '20px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-sm-leading-none-medium': {
    fontSize: '14px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '100%',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-base-regular': {
    fontSize: '16px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '24px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-base-medium': {
    fontSize: '16px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '24px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-base-semibold': {
    fontSize: '16px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '24px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-base-mono': {
    fontSize: '16px',
    textDecoration: 'none',
    fontFamily: 'DM Mono',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '24px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-base-underlined-regular': {
    fontSize: '16px',
    textDecoration: 'underline',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '24px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-base-underlined-medium': {
    fontSize: '16px',
    textDecoration: 'underline',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '24px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-lg-regular': {
    fontSize: '18px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-lg-medium': {
    fontSize: '18px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-lg-semibold': {
    fontSize: '18px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-lg-underlined': {
    fontSize: '18px',
    textDecoration: 'underline',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-lg-mono': {
    fontSize: '18px',
    textDecoration: 'none',
    fontFamily: 'DM Mono',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xl-regular': {
    fontSize: '20px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xl-medium': {
    fontSize: '20px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-xl-semibold': {
    fontSize: '20px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '28px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-2xl-regular': {
    fontSize: '24px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '32px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-2xl-medium': {
    fontSize: '24px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '32px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-2xl-semibold': {
    fontSize: '24px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '32px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-3xl-regular': {
    fontSize: '32px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '36px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-3xl-medium': {
    fontSize: '32px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '36px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-3xl-semibold': {
    fontSize: '32px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '36px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-4xl-regular': {
    fontSize: '40px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '400',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '44px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-4xl-medium': {
    fontSize: '40px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '44px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
  'text-4xl-semibold': {
    fontSize: '40px',
    textDecoration: 'none',
    fontFamily: 'DM Sans',
    fontWeight: '600',
    fontStyle: 'normal',
    fontStretch: 'normal',
    letterSpacing: '0%',
    lineHeight: '44px',
    paragraphIndent: 0,
    paragraphSpacing: 0,
    textCase: 'none',
  },
} as const;

export type TextStyles = typeof textStyles;
export type TextStyleName = keyof TextStyles;
